### ISSUE TITLE
regarding new access token

### ISSUE THREAD

**Issue by secretuser** [alphasp/pixiv-api-client#12]
I read your message about the depreciated login and the new access token that we have to use. 

I am really sorry to bother you about this, but I have trouble finding that access token / verifier in wireshark.

Could you perhaps show a screenshot of your wireshark GUI where I can find the access token? 
(or any other program is fine, I really need a clue so that I can know which line to look for). 
I tried searching for "token" / "access" keywords, but could not find it.
Is this access token on any pixiv page after login? 

Thank you in advance

**Comment by alphasp** [comment]
To get access token and refresh token, run wireshark, login with pixiv app, find a POST on `https://oauth.secure.pixiv.net/auth/token` from wireshark, you will be able to to get `access_token` and `refresh_token` from the response.

Altenatively, refer this python script https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362#file-pixiv_auth-py which help to automate the process to get tokens

**Comment by secretuser** [comment]
I got it working! thank you!

**Comment by Ishidres** [comment]
Thanks for the explanation! Using the python script above I can get the `refresh_token` and the `access_token`. However, when using the refresh_token in `pixiv.refreshAccessToken()` I get an error "invalid_grant" error:

```js
const PixivApi = require('pixiv-api-client');
const pixiv = new PixivApi();

process.on('unhandledRejection', error => {
  console.log('[unhandledRejection]:\n', error);
})
.on('uncaughtException', error => {
  console.log('[uncaughtException]:\n', error);
  process.exit(0);
});

pixiv.refreshAccessToken("refresh_token from python script").then(() => {
  // error
});
```
This is the error message:
```js
[unhandledRejection]:
 { has_error: true,
  errors: { system: { message: 'Invalid refresh token', code: 1508 } },
  error: 'invalid_grant' }
```

I tried several different refresh tokens using the method from the python script to ensure that the refresh token is not invalid, but the error persists. Any idea what is causing this? Am I using the refresh token in `pixiv.refreshAccessToken()` correctly?

Thanks in advance!

**Comment by Bintang73** [comment]
> Thanks for the explanation! Using the python script above I can get the `refresh_token` and the `access_token`. However, when using the refresh_token in `pixiv.refreshAccessToken()` I get an error "invalid_grant" error:
> 
> ```js
> const PixivApi = require('pixiv-api-client');
> const pixiv = new PixivApi();
> 
> process.on('unhandledRejection', error => {
>   console.log('[unhandledRejection]:\n', error);
> })
> .on('uncaughtException', error => {
>   console.log('[uncaughtException]:\n', error);
>   process.exit(0);
> });
> 
> pixiv.refreshAccessToken("refresh_token from python script").then(() => {
>   // error
> });
> ```
> 
> This is the error message:
> 
> ```js
> [unhandledRejection]:
>  { has_error: true,
>   errors: { system: { message: 'Invalid refresh token', code: 1508 } },
>   error: 'invalid_grant' }
> ```
> 
> I tried several different refresh tokens using the method from the python script to ensure that the refresh token is not invalid, but the error persists. Any idea what is causing this? Am I using the refresh token in `pixiv.refreshAccessToken()` correctly?
> 
> Thanks in advance!

how i get code and codeVerfier?
