### ISSUE TITLE
how i get code and codeVerifier

### ISSUE THREAD

**Issue by Bintang73** [alphasp/pixiv-api-client#13]
after i get access token in script  https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362#file-pixiv_auth-py which
how i get code and codeVerifier?

**Comment by alphasp** [comment]
There is no need to use `tokenRequest` api with `code` and `codeVerifier` unless you want to make client app.
By following the script, you will be able to get `refresh_token` too, then you just need pass the refresh token to `refreshToken` api to "login" and make other api request as usual.

**Comment by Bintang73** [comment]
> There is no need to use `tokenRequest` api with `code` and `codeVerifier` unless you want to make client app.
> By following the script, you will be able to get `refresh_token` too, then you just need pass the refresh token to `refreshToken` api to "login" and make other api request as usual.

ok its works, but image result 403 forbidden :(

**Comment by alphasp** [comment]
> > There is no need to use `tokenRequest` api with `code` and `codeVerifier` unless you want to make client app.
> > By following the script, you will be able to get `refresh_token` too, then you just need pass the refresh token to `refreshToken` api to "login" and make other api request as usual.
> 
> ok its works, but image result 403 forbidden :(

To view image, request to image need to set `referer` to `http://www.pixiv.net`  in HTTP request header
